#spring.jackson.serialization.write_dates_as_timestamps: false

#spring:
#  jackson:
#    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
#    serialization:
#      write-dates-as-timestamps: false